"""Changed Columns to match collections

Revision ID: 5d352e051c4e
Revises: f1f47bab2274
Create Date: 2025-08-22 22:33:32.562227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d352e051c4e'
down_revision = 'f1f47bab2274'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boost_factors', sa.Column('astrophysics_weight', sa.Float(), nullable=True))
    op.add_column('boost_factors', sa.Column('earthscience_weight', sa.Float(), nullable=True))
    op.add_column('boost_factors', sa.Column('planetary_weight', sa.Float(), nullable=True))
    op.add_column('boost_factors', sa.Column('astrophysics_final_boost', sa.Float(), nullable=True))
    op.add_column('boost_factors', sa.Column('earthscience_final_boost', sa.Float(), nullable=True))
    op.add_column('boost_factors', sa.Column('planetary_final_boost', sa.Float(), nullable=True))

    op.drop_column('boost_factors', 'planetary_science_final_boost')
    op.drop_column('boost_factors', 'astronomy_final_boost')
    op.drop_column('boost_factors', 'astronomy_weight')
    op.drop_column('boost_factors', 'earth_science_final_boost')
    op.drop_column('boost_factors', 'planetary_science_weight')
    op.drop_column('boost_factors', 'earth_science_weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boost_factors', sa.Column('earth_science_weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('boost_factors', sa.Column('planetary_science_weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('boost_factors', sa.Column('earth_science_final_boost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('boost_factors', sa.Column('astronomy_weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('boost_factors', sa.Column('astronomy_final_boost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('boost_factors', sa.Column('planetary_science_final_boost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    op.drop_column('boost_factors', 'planetary_final_boost')
    op.drop_column('boost_factors', 'earthscience_final_boost')
    op.drop_column('boost_factors', 'astrophysics_final_boost')
    op.drop_column('boost_factors', 'planetary_weight')
    op.drop_column('boost_factors', 'earthscience_weight')
    op.drop_column('boost_factors', 'astrophysics_weight')
    # ### end Alembic commands ### 